export const PROFILE_COLUMNS = [
	{
		index: 0,
		maxWidth: 80,
		minWidth: 48,
		width: 64,
		accessor: "name",
		Header: "Name",
		sortKeys: ["name"],
		isHidden: false,
		isSortable: true,
	},
	{
		index: 1,
		accessor: "shipping.line1",
		Header: "Shipping",
		sortKeys: ["shipping"],
		isHidden: false,
		isSortable: true,
	},
	{
		index: 2,
		accessor: "billing.line1",
		Header: "Billing",
		sortKeys: ["billing"],
		isHidden: false,
		isSortable: true,
	},
	{
		index: 3,
		accessor: "payment.email",
		Header: "Email",
		sortKeys: ["email"],
		isHidden: false,
		isSortable: true,
	},
	{
		index: 4,
		maxWidth: 112,
		minWidth: 64,
		width: 92,
		type: "card",
		accessor: "payment.number",
		Header: "Card",
		sortKeys: ["number"],
		isHidden: false,
		isSortable: true,
	},
];
