const sizes = [
  {
    label: "Generic",
    options: [{ value: "Random", label: "Random" }],
  },
  {
    label: "Clothing",
    options: [
      { value: "3XS", label: "3X-Small" },
      { value: "XXS", label: "2X-Small" },
      { value: "XS", label: "X-Small" },
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
      { value: "XXL", label: "2X-Large" },
      { value: "3XL", label: "3X-Large" },
    ],
  },
  {
    label: "Shoes",
    options: [
      { value: "3.5", label: "3.5" },
      { value: "4", label: "4.0" },
      { value: "4.5", label: "4.5" },
      { value: "5", label: "5.0" },
      { value: "5.5", label: "5.5" },
      { value: "6", label: "6.0" },
      { value: "6.5", label: "6.5" },
      { value: "7", label: "7.0" },
      { value: "7.5", label: "7.5" },
      { value: "8", label: "8.0" },
      { value: "8.5", label: "8.5" },
      { value: "9", label: "9.0" },
      { value: "9.5", label: "9.5" },
      { value: "10", label: "10.0" },
      { value: "10.5", label: "10.5" },
      { value: "11", label: "11.0" },
      { value: "11.5", label: "11.5" },
      { value: "12", label: "12.0" },
      { value: "12.5", label: "12.5" },
      { value: "13", label: "13.0" },
      { value: "13.5", label: "13.5" },
      { value: "14", label: "14.0" },
      { value: "14.5", label: "14.5" },
      { value: "15", label: "15.0" },
      { value: "16", label: "16.0" },
      { value: "17", label: "17.0" },
      { value: "18", label: "18.0" },
    ],
  },
];

export { sizes };
