export const getTaskColumns = (view: string) => [
	{
		id: "id",
		maxWidth: 48,
		minWidth: 48,
		width: 48,
		index: 0,
		accessor: "id",
		Header: "Task",
		sortKeys: ["id"],
		isHidden: false,
		isSortable: true,
	},
	{
		id: "store",
		maxWidth: 128,
		minWidth: 64,
		width: 96,
		index: 1,
		accessor: view === "Basic" ? "store.name" : "store",
		Header: "Store",
		sortKeys: ["name"],
		isHidden: false,
		isSortable: true,
	},
	{
		id: "profile",
		maxWidth: 128,
		minWidth: 64,
		width: 96,
		index: 2,
		accessor: view === "Basic" ? "profile.name" : "profile",
		Header: "Profile",
		sortKeys: ["name"],
		isHidden: false,
		isSortable: true,
	},
	{
		id: "proxies",
		maxWidth: 112,
		minWidth: 64,
		width: 80,
		index: 3,
		accessor: view === "Basic" ? "proxies.name" : "proxies",
		Header: "Proxies",
		sortKeys: ["name"],
		isHidden: false,
		isSortable: true,
	},
	{
		id: "product",
		maxWidth: 160,
		minWidth: 64,
		width: 128,
		index: 4,
		accessor: view === "Basic" ? "product.name" : "product",
		Header: "Product",
		isHidden: false,
		isSortable: true,
	},
	{
		id: "status",
		maxWidth: 128,
		minWidth: 64,
		width: 96,
		index: 5,
		accessor: "status",
		Header: "Status",
		sortKeys: ["status"],
		isHidden: false,
		isSortable: true,
	},
];

export const headers = [
	{ label: "Task", key: "id" },
	{ label: "Store", key: "store" },
	{ label: "Profile", key: "profile" },
	{ label: "Proxies", key: "proxies" },
	{ label: "Product", key: "product" },
	{ label: "Status", key: "status" },
];
